### ISSUE TITLE
can it be built in linux and dump cis?

### ISSUE THREAD

**Issue by youxiaojie** [cr1901/dumpcis#1]
can it be built in linux and dump cis?

**Comment by cr1901** [comment]
No, this program can't be built for Linux as-is.

It might be possible with `/dev/mem` and `ioperm`/`outb`/`inb` shenanigans, but it's not good practice. I don't plan to add this functionality.

That said, there's probably some sort of `ioctl` for reading PCMCIA CIS from Linux- I haven't looked into it.

**Comment by youxiaojie** [comment]
does this program run under bare dos or first I must load 5c475's driver for dos and then dump cis by this programm?

**Comment by cr1901** [comment]
@youxiaojie (Sorry, forgot to respond to this)

This program runs under bare DOS. 

You do not need to load a driver for your PCMCIA controller (and in fact, _I haven't tried running this program when another PCMCIA driver is running- **you do so at your own risk**._).

**Comment by youxiaojie** [comment]
great！I have a question, as far as I know, cis store in attributive mem, how computer recognise it? I see even address is attrib mems.
pcmcia has 26 pin address line, so 2^26=64MiB, if I made a 64MiB memory card, where store cis?

**Comment by cr1901** [comment]
I don't remember- it's been too long since I last worked on this and I would have to reread the PCMCIA spec again. Right now, I lack the bandwidth _and hardware_ to work on this. I want to say that PCMCIA doesn't support memory cards that big though, but I'm not 100% sure.
